services:
  jdcloud_ipq60xx_immwrt:
    image: immortalwrt/sdk:qualcommax-ipq60xx
    volumes:
      - .:/build
    command: bash build.sh jdcloud_ipq60xx_immwrt
    working_dir: /build
  jdcloud_ipq60xx_libwrt:
    image: immortalwrt/sdk:qualcommax-ipq60xx
    volumes:
      - .:/build
    command: bash build.sh jdcloud_ipq60xx_libwrt
    working_dir: /build  
  x64_immwrt:
    image: immortalwrt/sdk:x86_64
    volumes:
      - .:/build
    command: bash build.sh x64_immwrt
    working_dir: /build
  mediatek-filogic-openwrt-24.10:
    image: immortalwrt/sdk:mediatek-filogic-openwrt-24.10
    volumes:
      - .:/build
    command: bash build.sh cudy_tr3000
    working_dir: /build