services:
  jdcloud_ipq60xx_immwrt:
    image: immortalwrt/sdk:qualcommax-ipq60xx
    volumes:
      - .:/build
      - jdcloud_ipq60xx_immwrt-builddir:/build/imm-nss
    command: bash build.sh jdcloud_ipq60xx_immwrt
    working_dir: /build
  jdcloud_ipq60xx_libwrt:
    image: immortalwrt/sdk:qualcommax-ipq60xx
    volumes:
      - .:/build
      - jdcloud_ipq60xx_libwrt-builddir:/build/libwrt-k612
    command: bash build.sh jdcloud_ipq60xx_libwrt
    working_dir: /build  
  x64_immwrt:
    image: immortalwrt/sdk:x86_64
    volumes:
      - .:/build
      - immortalwrt-builddir:/build/immortalwrt
    command: bash build.sh x64_immwrt
    working_dir: /build
volumes:
  jdcloud_ipq60xx_immwrt-builddir:
  jdcloud_ipq60xx_libwrt-builddir:
  immortalwrt-builddir: