src/gz openwrt_base https://mirror.nju.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/base
src/gz openwrt_luci https://mirror.nju.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/luci
src/gz openwrt_packages https://mirror.nju.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/packages
src/gz openwrt_routing https://mirror.nju.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/routing
src/gz openwrt_telephony https://mirror.nju.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/telephony
