src/gz openwrt_base https://downloads.immortalwrt.org/releases/{VERSION}/packages/{ARCH}/base
src/gz openwrt_luci https://downloads.immortalwrt.org/releases/{VERSION}/packages/{ARCH}/luci
src/gz openwrt_packages https://downloads.immortalwrt.org/releases/{VERSION}/packages/{ARCH}/packages
src/gz openwrt_routing https://downloads.immortalwrt.org/releases/{VERSION}/packages/{ARCH}/routing
src/gz openwrt_telephony https://downloads.immortalwrt.org/releases/{VERSION}/packages/{ARCH}/telephony
