src/gz openwrt_base https://mirrors.ustc.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/base
src/gz openwrt_luci https://mirrors.ustc.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/luci
src/gz openwrt_packages https://mirrors.ustc.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/packages
src/gz openwrt_routing https://mirrors.ustc.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/routing
src/gz openwrt_telephony https://mirrors.ustc.edu.cn/immortalwrt/releases/{VERSION}/packages/{ARCH}/telephony
