name: Weekly Release WRT
run-name: Weekly Release WRT

on:
  # schedule:
  #   - cron: "0 4 * * 5"
  workflow_dispatch: {}

permissions:
  actions: write
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        model:
          - lk_x64_immwrt
          - lk_ct3003_mt798x
          - lk_ct3003_mt798x_6.6
          - lk_jdcloud_ax6000_mt798x
          - lk_jdcloud_ax6000_mt798x-6.6
          - lk_jdcloud_ax6000_immwrt
          - lk_jdcloud_ipq60xx_immwrt
          - lk_jdcloud_ipq60xx_libwrt
    uses: ./.github/workflows/release_wrt.yml
    with:
      model: ${{ matrix.model }}
    secrets: inherit
