name: Weekly Release WRT
run-name: Weekly Release WRT

on:
  # schedule:
  #   - cron: "0 4 * * 5"
  workflow_dispatch: {}

permissions:
  actions: write
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        model:
          - lk_x64_immwrt
          - lk_mediatek_immwrt
          - lk_mediatek_immwrt_mini
          - lk_mt798x_7986_rebase
          - lk_mt798x_7986_k6.6
          - lk_mt798x_7986_rebase_mini
          - lk_mt798x_7986_k6.6_mini
          - lk_mt798x_7981_rebase_mini
          - lk_mt798x_7981_k6.6_mini
          - lk_jdcloud_ipq60xx_libwrt
          - lk_ipq807x_libwrt
          - lk_ipq807x_libwrt_mini
          # - lk_jdcloud_ipq60xx_immwrt
    uses: ./.github/workflows/release_wrt.yml
    with:
      model: ${{ matrix.model }}
    secrets: inherit
